### ISSUE TITLE
Better page styles

### ISSUE THREAD

**Issue by pitr** [pitr/gemini-ios#13]
Original feedback from @LukeEmmet:
> A few minor typographical thoughts: hanging indents for bullets, side bar for quotations would be nice

> Less white space between preformatted lines, so that ascii art doesnt have blank bands across it.

**Comment by pitr** [comment]
fixes in 9f28ab421beac88b26f51b46895924502599a02b 33f0a0097e19613e30162fe7b91059c91b58aed7 915f727595af505a3a3cd430f952bd565db3c5ee 7f897daebbb05433fd71348f2302ca363ee5b129

**Comment by LukeEmmet** [comment]
great stuff - I look forward to seeing the updates
