### ISSUE TITLE
app crashing when navigating to domain

### ISSUE THREAD

**Issue by neurosnap** [pitr/gemini-ios#19]
Hey!  Great ios app.  I set up my gemini capsule and it works on other desktop clients (e.g. bombadillo and lagrange) but elaho crashes when I go to it.

Now, elaho keeps crashing because it loads the browser from history.

gemini://erock.io

**Comment by pitr** [comment]
thank you for reporting, I have a fix for it, will go out in a few days as soon as I submit it into the app store

In the meantime what I would recommend is open Elaho in flight mode (with wifi/cellular turned off) and closing that tab

**Comment by mcpcpc** [comment]
not sure if this is the same or different issue. 

Steps to reproduce:
1. Navigate to an invalid page (e.g. gemini://oh.my)
2. Select the navigation bar and choose a website from the “Top Sites” (gemini://geddit.glv.one)
3. Elaho will crash immediately or shortly after.

**Comment by pitr** [comment]
hey @mcpcpc I replied to your email but my reply keeps bouncing. I was able to reproduce and fix the issue you mentioned - aff86dce

**Comment by pitr** [comment]
v1.4 was released into App Store with this fix
