### ISSUE TITLE
ANSI Escape color codes

### ISSUE THREAD

**Issue by pitr** [pitr/gemini-ios#20]
for reference https://en.wikipedia.org/wiki/ANSI_escape_code#SGR

should be off by default and enabled with a setting

**Comment by pitr** [comment]
fixed by 7adb617ec66f04aec6b85120f5e917093a2d3873 and f63821bb8251278de6c20ca05ae6414998130766

**Comment by hadibus** [comment]
Great project. Glad there's a gemini browser for iOS 😀

It appears that this is working for preformatted text, but is not working in regular paragraphs. 

Lagrange renders colors in paragraphs. See sentence at bottom "Today's blessed color is blue."
![pic-selected-220220-2104-01](https://user-images.githubusercontent.com/14830474/154887322-0c994ac3-6ed6-4b6f-99e2-55e9bd908191.png)

The same sentence in Elaho is rendered as "Today's blessed color is [38;5;81mblue[0m."
