### ISSUE TITLE
Elaho Crash when navigating with the Up button

### ISSUE THREAD

**Issue by mcpcpc** [pitr/gemini-ios#25]
* **Current Version**: Elaho 1.3
* **Issue**: App crashes when using the Up botton certain pages.  
* **To reproduce**: 
1. navigate to the following page, gemini://erock.io/2021/03/04/adventure-into-gemini-as-fe-engineer.gmi
2. press the Up button.

**Comment by pitr** [comment]
same issue as #19, server responds with status code "20" without mime time. Fixed in master

**Comment by mcpcpc** [comment]
Thanks for the quick response. Sorry for the potential duplicate issue.  I am not at all familiar with app development in iOS but, out if curiosity, how does the git master version track to the release version in the iOS app store?

**Comment by mcpcpc** [comment]
Thanks for the quick response. I should have checked the milestones for the v1.4 release as I naively assumed the master tracked to the iOS App Store release version.  Sorry for creating a duplicate issue =).

**Comment by pitr** [comment]
v1.4 was just released to the store, closing
