### ISSUE TITLE
The operation couldn’t be completed. (Network.NWError error 0.)

### ISSUE THREAD

**Issue by Tiitu** [pitr/gemini-ios#30]
The app is giving the following error message on an iPad Pro and no sites can be opened:

"The operation couldn’t be completed. (Network.NWError error 0.)"

I did install the app from the Apple App Store just a moment ago for the first time.

**Comment by Tiitu** [comment]
After trying several times, and, disabling the Cloudflare 1.1.1.1 app and enabling the Cloudflare Warp instead, and fiddling with the settings in both the Elaho Gemini and Warp iOS apps, the Elaho suddenly started to run fine.

Now, I am quite happy that I came back after first removing Elaho disappointedly from my iPad.

Good work guys!

**Comment by pitr** [comment]
I will check out cloudflare apps and see if I can replicate it

**Comment by Tiitu** [comment]
👌

**Comment by pitr** [comment]
Hmm I wasn't able to replicate the issue with either 1.1.1.1 or WASP enabled. I closed-opened Elaho every time I made a change to the settings (per recommendation from Cloudflare docs).

**Comment by Tiitu** [comment]
This is then good!

But, here is an other one: Long pressing any of the Top Sites on the start page and then pressing Remove, jumps out without removing it!

T
